name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 14 days with no activity. Remove the stale label or comment or this will be closed in 7 days'
        stale-pr-message: 'This Pull Request is stale because it has been open 14 days with no activity. Remove the stale label or comment or this will be closed in 7 days'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 14
        days-before-close: 7
